---
- name: Rancher 2 Load Balancers
  hosts: rancher_2_kubernetes_load_balancers
  become: yes
  become_user: root
  become_method: sudo

  vars:
    users:
      - username: rancherk8s
        name: Load Balancer
        password: "{{ lookup('ini', 'password section=rancher_2_kubernetes_node file=secrets.ini') }}"
        groups: ['docker']
        uid: 1001
        ssh_key:
          - "{{ lookup('ini', 'ssh_key section=rancher_2_kubernetes_node file=secrets.ini') }}"

    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "443"
      - "2376"
      - "2379"
      - "2380"
      - "6443"
      - "9099"
      - "10248"
      - "10250"
      - "10254"
        # Application ports
      - "8443"
    firewall_allowed_udp_ports:
      - "8472"
    firewall_additional_rules:
      - "iptables -A INPUT -p tcp --match multiport --dports 30000:32767 -j ACCEPT"
      - "iptables -A INPUT -p udp --match multiport --dports 30000:32767 -j ACCEPT"


    nginx_installation_type: configuration-only

    nginx_worker_rlimit_nofile: 40000

    nginx_events_params:
      - worker_connections 8192

    nginx_sites:
      server:
        - listen 80
        - return 301 https://$host$request_uri

    suppress_default_site: true

    nginx_stream_configs:
      upstream:
        - upstream rancher_servers {
            least_conn;
            {% for host in groups['rancher_2_kubernetes_nodes'] %} 
              server {{ hostvars[host]['ansible_host'] }}:443 max_fails=3 fail_timeout=5s;
            {% endfor %}
          }
      server:
        - server {
            listen 443;
            proxy_pass rancher_servers;
          }

  pre_tasks:
    - name: Update apt cache before anything is done
      apt:
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"

  tasks:
    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present

  roles: 
  # - rancher.common
  # - geerlingguy.firewall
  - geerlingguy.docker
  - singleplatform-eng.users
  # - nginxinc.nginx
  # - jdauphant.nginx
