---
- name: Rancher 2 Kubernetes Server
  hosts: rancher_2_kubernetes_nodes
  become: yes
  become_user: root
  become_method: sudo

  vars:
    docker_users:
      - ubuntu
    
    users:
      - username: rancherk8s
        name: Rancher Kubernetes
        password: "{{ lookup('ini', 'password section=rancher_2_kubernetes_node file=secrets.ini') }}"
        groups: ['docker']
        uid: 1001
        ssh_key:
          - "{{ lookup('ini', 'ssh_key section=rancher_2_kubernetes_node file=secrets.ini') }}"

    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "443"
      - "2376"
      - "2379"
      - "2380"
      - "6443"
      - "9099"
      - "10250"
      - "10254"
        # Application ports
      - "8443"
    firewall_allowed_udp_ports:
      - "8472"
    firewall_additional_rules:
      - "iptables -A INPUT -p tcp --match multiport --dports 30000:32767 -j ACCEPT"
      - "iptables -A INPUT -p udp --match multiport --dports 30000:32767 -j ACCEPT"

  tasks:
    - name: Update apt cache before anything is done
      apt:
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"


  roles: 
    - geerlingguy.firewall
    - geerlingguy.docker
    - singleplatform-eng.users
    - rancher.rke_cluster

